### ISSUE TITLE
There is a way to specify: exclude_dir?

### ISSUE THREAD

**Issue by eriknyk** [Rowno/grunt-mocha-cli#28]
Hi,
There is a way to specify: exclude_dir?
just because I have a features/ directory inside test/ directory
I have mock object or some another resources that is being used on tests,
I wan't a way to specify to mocha exclude that directory,because it is considering  as test,.
and errors was thrown.

Best Regards.

**Comment by Rowno** [comment]
Just use a [negative glob](http://gruntjs.com/configuring-tasks#globbing-patterns). E.g:

```js
grunt.initConfig({
    mochacli: {
        all: [
            'test/**/*.js',
            '!test/features/**/*'
        ]
    }
});
```
