### ISSUE TITLE
Running with ndebug, harmony stops working

### ISSUE THREAD

**Issue by Sherlock92** [Rowno/grunt-mocha-cli#29]
When running with the following configuration ..

```
options: {
    reporter: 'nyan',
    //ndebug: true,
    harmony: true,
    bail: true
}
```

.. things are pretty good. But when enabling `ndebug` for some reason I get an `Unexpected Token` error on arrow functions. 

```
options: {
    reporter: 'nyan',
    ndebug: true,
    harmony: true,
    bail: true
}
```

I can see the args being passed look correct:

`[ 'debug',
  '--bail',
  '--harmony',
  '--reporter',
  'nyan',
  'test/schema-test.js' ]`

Is this a bug, or is there maybe something wrong with my configuration ?

Thanks!

**Comment by Rowno** [comment]
I created this simple test with arrow functions and ran it directly with `mocha`:
```js
'use strict';

describe('Array', () => {
    describe('#indexOf()', () => {
        it('should return -1 when the value is not present', () => console.log('test'));
    });
});
```

It runs fine with `mocha --harmony test.js` but errors with `mocha debug --harmony test.js`, so this must be a bug in Mocha. As a workaround, using `--debug` instead with `node-inspector` works fine, so you could use the `debug` option instead.
