### ISSUE TITLE
Add support for `harmony_scoping` node option

### ISSUE THREAD

**Issue by basicdays** [Rowno/grunt-mocha-cli#30]
In node v0.12, it has an option to enable harmony scoping (e.g. let and const). Command line can enable it like this: `node --harmony_scoping`.

**Comment by Rowno** [comment]
Looks like [Mocha doesn't support the harmony_scoping option][harmony-options] yet.

[harmony-options]: https://github.com/mochajs/mocha/blob/master/bin/_mocha#L84-L92
