### ISSUE TITLE
How to generate html report and wirte to folder

### ISSUE THREAD

**Issue by tomalex0** [Rowno/grunt-mocha-cli#37]
How can we output html report to a file  for reference?

This is how my config looks, is there a way to output the result?
```
{
        src: ['test/unit/**/*.js'],
        options: {
            timeout: 6000,
            'check-leaks': true,
            ui: 'bdd',
            reporter: 'doc'

        }
    }
```

**Comment by tomalex0** [comment]
I have used https://www.npmjs.com/package/mochawesome  with cli and it worked fine

**Comment by Rowno** [comment]
You can use the `save` option.
