### ISSUE TITLE
Update mocha to v4

### ISSUE THREAD

**Issue by kirrg001** [Rowno/grunt-mocha-cli#43]
Hey!

Is it possible that you update mocha from v3 to v4?

If your tests are running with mocha v4, then you can run into [this issue](https://github.com/mochajs/mocha/issues/3044).

Thank you!
Kate

**Comment by Rowno** [comment]
Done in version [4.0.0](https://github.com/Rowno/grunt-mocha-cli/releases/tag/v4.0.0)!
