### ISSUE TITLE
Unable to repeat the same test file multiple times

### ISSUE THREAD

**Issue by agusgambina** [Rowno/grunt-mocha-cli#47]
I am trying to run programmatically a test case scenario. I realized that each file is only running once. Here is my example

```
module.exports = function(grunt) {
  require('load-grunt-tasks')(grunt);

  grunt.initConfig({
    mochacli: {
      options: {
        bail: false,
        colors: true,
        // timeout: 900000
      },
      files: [
        'test/adminLogin.spec.js',
        
        'test/createUser.spec.js',
        'test/deleteUser.spec.js',
        
        'test/createUser.spec.js',
        'test/updateUserUser.spec.js',
        'test/deleteUser.spec.js',

        'test/createUser.spec.js',
      ]
    }
  });
  grunt.registerTask('default', ['mochacli']);
};
```

I have this scenario where I want to test different files and some of them multiple time. but when I run grunt, each file is only executed once.

**Comment by Rowno** [comment]
Why do you want to run a test file multiple times? This looks like a very unusual testing setup.

**Comment by agusgambina** [comment]
@Rowno thanks for the answer

I agree that maybe it is not the usual flow. But in my case I want to have an scenario where I test everything and that would involve to create a resource, delete it, and re create it again.

In my case each file represents a different call to an endpoint.

Thanks

**Comment by Rowno** [comment]
The normal way of doing that is to have a test helpers file that exports functions that do those things. You can then import those functions into your test files and call them in the [`before` and `after` hooks](https://mochajs.org/#hooks).

**Comment by agusgambina** [comment]
Thanks for the answer!
